### ISSUE TITLE
Crash on native side

### ISSUE THREAD

**Issue by borconi** [jwoolston/Android-Libusb-Wrapper#17]
Love the library works wonderful, however on some device I get a native crash, and not quite sure why, when I'm trying to open the device like:

```
final com.jwoolston.android.libusb.UsbManager manager = new com.jwoolston.android.libusb.UsbManager(getApplicationContext());
            final UsbDeviceConnection connection = manager.registerDevice(device);

```

```
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art: JNI DETECTED ERROR IN APPLICATION: non-zero capacity for nullptr pointer: 32
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     in call to NewDirectByteBuffer
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     from java.nio.ByteBuffer com.jwoolston.android.libusb.UsbInterface.nativeGetEndpoint(java.nio.ByteBuffer, int)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art: "main" prio=5 tid=1 Runnable
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   | group="main" sCount=0 dsCount=0 obj=0x74a37fb0 self=0x7fa63fc400
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   | sysTid=8602 nice=0 cgrp=default sched=0/0 handle=0x7faa1312c0
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   | state=R schedstat=( 944594530 89590922 814 ) utm=84 stm=10 core=1 HZ=100
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   | stack=0x7fefc1f000-0x7fefc21000 stackSize=8MB
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   | held mutexes= "mutator lock"(shared held)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at com.jwoolston.android.libusb.UsbInterface.nativeGetEndpoint(Native method)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at com.jwoolston.android.libusb.UsbInterface.fromNativeDescriptor(UsbInterface.java:233)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at com.jwoolston.android.libusb.UsbInterface.fromNativeObject(UsbInterface.java:204)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at com.jwoolston.android.libusb.UsbConfiguration.fromNativeObject(UsbConfiguration.java:206)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at com.jwoolston.android.libusb.UsbDevice.populate(UsbDevice.java:390)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at com.jwoolston.android.libusb.UsbManager.registerDevice(UsbManager.java:100)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   - locked <0x0bb607cc> (a java.lang.Object)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at gb.xxy.hr.MainActivity.communicateWithDevice(MainActivity.java:549)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at gb.xxy.hr.MainActivity$10.onReceive(MainActivity.java:596)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:   - locked <0x027ce56e> (a gb.xxy.hr.MainActivity$10)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:922)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at android.os.Handler.handleCallback(Handler.java:815)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at android.os.Handler.dispatchMessage(Handler.java:104)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at android.os.Looper.loop(Looper.java:207)
06-14 12:56:35.355 8602-8602/gb.xxy.hr E/art:     at android.app.ActivityThread.main(ActivityThread.java:5737)
06-14 12:56:35.356 8602-8602/gb.xxy.hr E/art:     at java.lang.reflect.Method.invoke!(Native method)
06-14 12:56:35.356 8602-8602/gb.xxy.hr E/art:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-14 12:56:35.356 8602-8602/gb.xxy.hr E/art:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
06-14 12:56:35.356 8602-8602/gb.xxy.hr D/AEE/LIBAEE: shell: connected with AED OK
06-14 12:56:35.359 8602-8602/gb.xxy.hr D/AEE/LIBAEE: shell: got the request (cmd:Ind,AE_IND_LOG_CLOSE)
06-14 12:56:35.359 8602-8602/gb.xxy.hr D/AEE/LIBAEE: shell: Got session close ind from AED
06-14 12:56:35.359 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441] JNI DETECTED ERROR IN APPLICATION: non-zero capacity for nullptr pointer: 32
06-14 12:56:35.359 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]     in call to NewDirectByteBuffer
06-14 12:56:35.359 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]     from java.nio.ByteBuffer com.jwoolston.android.libusb.UsbInterface.nativeGetEndpoint(java.nio.ByteBuffer, int)
06-14 12:56:35.359 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441] "main" prio=5 tid=1 Runnable
06-14 12:56:35.359 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   | group="main" sCount=0 dsCount=0 obj=0x74a37fb0 self=0x7fa63fc400
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   | sysTid=8602 nice=0 cgrp=default sched=0/0 handle=0x7faa1312c0
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   | state=R schedstat=( 944594530 89590922 814 ) utm=84 stm=10 core=1 HZ=100
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   | stack=0x7fefc1f000-0x7fefc21000 stackSize=8MB
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   | held mutexes= "mutator lock"(shared held)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.jwoolston.android.libusb.UsbInterface.nativeGetEndpoint(Native method)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.jwoolston.android.libusb.UsbInterface.fromNativeDescriptor(UsbInterface.java:233)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.jwoolston.android.libusb.UsbInterface.fromNativeObject(UsbInterface.java:204)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.jwoolston.android.libusb.UsbConfiguration.fromNativeObject(UsbConfiguration.java:206)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.jwoolston.android.libusb.UsbDevice.populate(UsbDevice.java:390)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.jwoolston.android.libusb.UsbManager.registerDevice(UsbManager.java:100)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   - locked <0x0bb607cc> (a java.lang.Object)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at gb.xxy.hr.MainActivity.communicateWithDevice(MainActivity.java:549)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at gb.xxy.hr.MainActivity$10.onReceive(MainActivity.java:596)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   - locked <0x027ce56e> (a gb.xxy.hr.MainActivity$10)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:922)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at android.os.Handler.handleCallback(Handler.java:815)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at android.os.Handler.dispatchMessage(Handler.java:104)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at android.os.Looper.loop(Looper.java:207)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at android.app.ActivityThread.main(ActivityThread.java:5737)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at java.lang.reflect.Method.invoke!(Native method)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
06-14 12:56:35.360 8602-8602/gb.xxy.hr A/art: art/runtime/java_vm_ext.cc:441] 

```

**Comment by borconi** [comment]
Ok, this might have been caused by multidexing as I was importing the aar into my app, I've now included the source code and rebuilt it and that looks to work fine. I'll double check and if indeed this is the case I will close the issue.

**Comment by jwoolston** [comment]
> Ok, this might have been caused by multidexing as I was importing the aar into my app, I've now included the source code and rebuilt it and that looks to work fine. I'll double check and if indeed this is the case I will close the issue.

Interesting. Thankyou for the update on it. I will be spending a good deal more time with this project in the future due to needs for work so I will be see to experiment with this. Please let me know if you encounter any additional troubles.

**Comment by borconi** [comment]
Hi. I can confirm that indeed this is a very strange behaviour, if I export the aar and use the imported aar in my project, on some devices I face the above native crash. 
If instead of importing the aar, I do copy all the code to my project and compile it all together it seems to work just fine an all devices. 

I'm still trying to get to the bottom of configuring pro-guard with it tough as if I do enable pro-guard it definitely breaks it all. 

Let me know what info you need from me (if any) happy to share code and project with you if you want to debug it.

**Comment by borconi** [comment]
> > Ok, this might have been caused by multidexing as I was importing the aar into my app, I've now included the source code and rebuilt it and that looks to work fine. I'll double check and if indeed this is the case I will close the issue.
> 
> Interesting. Thankyou for the update on it. I will be spending a good deal more time with this project in the future due to needs for work so I will be see to experiment with this. Please let me know if you encounter any additional troubles.


Edit:
- I've did multiple tests and finally decided to deploy the mobile test app provided with the library. When I install the debug run of it, it works fine on all device, when I build a release with gradle or generate a signed apk, the same JNI error appears again on some devices, but not on all. This does explain why it suddenly started working when I imported the library code rather then the aar file, as the aar file was a release build, but when I imported the code and I was testing I was actually deploying test builds.

Now doing some research, it looks like some variables are not getting initialised correctly when using release build, or better said in the debug build they a re forcefully initialised. Sadly my C skills are as non-existing so it will be pretty difficult for me to pinpoint where is this actually happening. However I hope that this might help you locate the issue/bug. I will post any update here if I can figure it out.

**Comment by jwoolston** [comment]
Yes that does narrow it down considerably. Frankly its not all that surprising as when I last worked on this I don't think I had even attempted a release build.

**Comment by borconi** [comment]
Well I'm using it now in my code instead of the built in Usb interface, simply because I want to be able to get more information when there are problems communicating with devices, in other words I'm only using the BulkTransfer from it and even that in a sync mode, however I find it more usable then the native one, so I do hope either you (or I) can get to the bottom of it, as it looks like I'm going to stick with this for my app.

**Comment by jwoolston** [comment]
That is exactly why I made this library. I got tired of -1 being the error
code for everything because Google was too lazy to provide the underlying
error so that's great to hear. Next week will be the start of the Sprint at
work that utilizes this so I would expect to see it resolved in the next
week or two. I will make sure to do everything with release builds to force
the issue to the forefront.

**Comment by borconi** [comment]
I did try to have a look and figure it out on what's happening. What I was able to understand till now is that, in the function ```Java_com_jwoolston_android_libusb_UsbInterface_nativeGetEndpoint``` the ```descriptor->endpoint``` is NULL, adding a simple check with ifnull and calling calloc does fix this native crash but it's still not OK.

As I said my C is non existing, but to me it feels like this object here doesn't get initiated somehow:
  ```
struct libusb_interface_descriptor *descriptor = (struct libusb_interface_descriptor *)
            (*env)->GetDirectBufferAddress(env, nativeDescriptor);
```

The ```nativeDescriptor``` object passed from Java to C looks OK to me....

**Comment by jwoolston** [comment]
You are somewhat correct in that it does not get initialized. More specifically, it is a lazy initialization so my guess is the particular code path has resulted in that lazy init not being triggered. That is useful information, thankyou.

**Comment by jwoolston** [comment]
@borconi The devices I have readily available don't seem to reproduce this. I don't doubt that it happens though. Can you give me a list of devices you are seeing this on?

**Comment by borconi** [comment]
Don't kno all of them as I've got reports from my app users as well, and for sure out of all my devices I can only reproduce it on 2 of them. One is an rsnav (an Android powered headunit for Audi) and the other is a nexus 7 with a really old ROM, I'll post the link to the ROM if you need it. Most of my clients use Android powered car headunits and as far as I could tell it mainly happens on rockchip units. If you need I can set up a remote access and test environment for you. happy to assist in any way I can.

**Comment by jwoolston** [comment]
First of all, its is awesome to see this being used for such an unexpected use case. 

Based on what you have described I decided to do a little research. The documentation for `GetDirectBufferAddress` is as follows:

>Returns the starting address of the memory region referenced by the buffer. Returns NULL if the memory region is undefined, if the given object is not a direct java.nio.Buffer, or if JNI access to direct buffers is not supported by this virtual machine.

When you say the `nativeDescriptor` passed from Java to C is ok, is that based on it not being `NULL` since it makes it past the null check? Could you try logging the result of `nativeDescriptor.isDirect();` in `UsbInterface#fromNativeDescriptor` to verify that it was correctly allocated as a native byte buffer? 

I happen to have a first generation Nexus 7. Is that the device or is it a second generation one?

As a side note, I am in the process of restructuring the project to support generic Java use as well. I will endeavor to leave the minimum API as low as possible but what min API are you using? I would hate to break your usage of it.

**Comment by borconi** [comment]
Sorry I had a really busy weekend and Monday I will try to do this tomorrow.
Yes it's a Gen 1 Nexus I'm using and the ROM is: CM 10.1-20130817-USBROM-grouper

As for the API I'm currently targeting 16+ and if you are curious about the app, this is it:
https://play.google.com/store/apps/details?id=gb.xxy.hr if interested I can share the repo with you. I'll update once I manage to do the logs.

**Comment by jwoolston** [comment]
@borconi No worries, I know the feeling. Thankyou for being patient with this as well. I will see if I can get my Nexus 7 to reproduce the issue, with or without that ROM. I took a look at the play store listing. If I am understanding correctly does the app allow you to use an Android device as an Android Auto target? If so that is awesome and I'm going throw this in my truck. 

Let me see what I can reproduce on my end before you go through the trouble of repo access or setting up a remote access but in the meantime, why don't you shoot me a direct email to make things easier. See my profile for the address.

**Comment by borconi** [comment]
Updating NDK to 20.0.5594570 fixed the issue. Thanks for all the support offered.
